// <auto-generated />
using System;
using Feedlot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Feedlot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FeedlotDbContext))]
    partial class FeedlotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("feedlot")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Feedlot.Domain.Entities.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_identificacion");

                    b.Property<string>("EstadoProductivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_productivo");

                    b.Property<string>("EstadoSanitario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_sanitario");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroArete")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_arete");

                    b.Property<decimal>("PesoIngreso")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("peso_ingreso_kg");

                    b.Property<decimal>("PrecioCompra")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_compra");

                    b.Property<string>("Raza")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("raza");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sexo");

                    b.Property<string>("precio_compra_moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("COP")
                        .HasColumnName("precio_compra_moneda");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIdentificacion")
                        .IsUnique()
                        .HasDatabaseName("ix_animals_codigo_identificacion");

                    b.ToTable("animals", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.AnimalLote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("es_activo");

                    b.Property<DateOnly?>("FechaEgreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_egreso");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("lote_id");

                    b.Property<string>("MotivoEgreso")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("motivo_egreso");

                    b.Property<string>("MotivoIngreso")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("motivo_ingreso");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId", "EsActivo")
                        .HasDatabaseName("ix_animal_lotes_animal_activo");

                    b.HasIndex("LoteId", "EsActivo")
                        .HasDatabaseName("ix_animal_lotes_lote_activo");

                    b.ToTable("animal_lotes", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.Compra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CantidadCabezas")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_cabezas");

                    b.Property<decimal?>("CantidadInsumo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad_insumo");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("costo_total");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("lote_id");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("moneda");

                    b.Property<decimal?>("PesoPromedioKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("peso_promedio_kg");

                    b.Property<decimal?>("PrecioPorCabeza")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_por_cabeza");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("TipoCompra")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo_compra");

                    b.Property<string>("TipoInsumo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_insumo");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_compras_fecha");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_compras_proveedor");

                    b.HasIndex("TipoCompra")
                        .HasDatabaseName("ix_compras_tipo");

                    b.ToTable("compras", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.Comprador", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contacto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contacto");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("ix_compradores_nombre");

                    b.ToTable("compradores", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.ConsumoAlimenticio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CantidadKg")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("cantidad_kg");

                    b.Property<decimal>("CostoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("costo_total");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("lote_id");

                    b.Property<Guid>("RacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("racion_id");

                    b.Property<Guid>("RegistradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por_id");

                    b.Property<string>("costo_moneda")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("COP")
                        .HasColumnName("costo_moneda");

                    b.HasKey("Id");

                    b.HasIndex("LoteId", "Fecha")
                        .HasDatabaseName("ix_consumos_lote_fecha");

                    b.ToTable("consumos_alimenticios", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.CostoOperativo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("categoria");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("concepto");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("lote_id");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("RegistradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por_id");

                    b.Property<string>("monto_moneda")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("COP")
                        .HasColumnName("monto_moneda");

                    b.HasKey("Id");

                    b.HasIndex("LoteId", "Fecha")
                        .HasDatabaseName("ix_costos_operativos_lote_fecha");

                    b.ToTable("costos_operativos", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.EventoSanitario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("diagnostico");

                    b.Property<DateOnly>("FechaEvento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_evento");

                    b.Property<DateOnly?>("ProximaDosis")
                        .HasColumnType("date")
                        .HasColumnName("proxima_dosis");

                    b.Property<string>("Responsable")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("responsable");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severidad");

                    b.Property<string>("TipoEvento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_evento");

                    b.Property<string>("Tratamiento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tratamiento");

                    b.HasKey("Id");

                    b.HasIndex("ProximaDosis")
                        .HasDatabaseName("ix_eventos_sanitarios_proxima_dosis")
                        .HasFilter("\"proxima_dosis\" IS NOT NULL");

                    b.HasIndex("Severidad")
                        .HasDatabaseName("ix_eventos_sanitarios_severidad");

                    b.HasIndex("AnimalId", "FechaEvento")
                        .HasDatabaseName("ix_eventos_sanitarios_animal_fecha");

                    b.ToTable("eventos_sanitarios", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostoKg")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("costo_kg");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("ProteinaPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("proteina_pct");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad_medida");

                    b.Property<string>("costo_moneda")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("COP")
                        .HasColumnName("costo_moneda");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_ingredientes_nombre");

                    b.ToTable("ingredientes", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_maxima");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_lotes_codigo");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_lotes_estado");

                    b.ToTable("lotes", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.Pesaje", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateOnly>("FechaPesaje")
                        .HasColumnType("date")
                        .HasColumnName("fecha_pesaje");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("Peso")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("peso_kg");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId", "FechaPesaje")
                        .HasDatabaseName("ix_pesajes_animal_fecha");

                    b.ToTable("pesajes", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contacto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contacto");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("ix_proveedores_nombre");

                    b.ToTable("proveedores", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.Racion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<decimal>("CostoKg")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("costo_kg");

                    b.Property<decimal>("EnergiaMcal")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("energia_mcal");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("ProteinaPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("proteina_pct");

                    b.Property<string>("costo_moneda")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("COP")
                        .HasColumnName("costo_moneda");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_raciones_nombre");

                    b.ToTable("raciones", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.RacionIngrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingrediente_id");

                    b.Property<decimal>("ProporcionPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("proporcion_pct");

                    b.Property<Guid>("RacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("racion_id");

                    b.HasKey("Id");

                    b.HasIndex("RacionId", "IngredienteId")
                        .IsUnique()
                        .HasDatabaseName("ix_racion_ingredientes_unique");

                    b.ToTable("racion_ingredientes", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("comprador_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("moneda");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId")
                        .HasDatabaseName("ix_ventas_comprador");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_ventas_fecha");

                    b.ToTable("ventas", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.VentaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<decimal>("PesoVentaKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("peso_venta_kg");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_venta");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venta_id");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("ix_venta_items_animal");

                    b.HasIndex("VentaId")
                        .HasDatabaseName("ix_venta_items_venta");

                    b.ToTable("venta_items", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre");

                    b.ToTable("roles", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Infrastructure.Identity.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "feedlot");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.AnimalLote", b =>
                {
                    b.HasOne("Feedlot.Domain.Entities.Lote", null)
                        .WithMany("AnimalesLote")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.EventoSanitario", b =>
                {
                    b.HasOne("Feedlot.Domain.Entities.Animal", null)
                        .WithMany("EventosSanitarios")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.Pesaje", b =>
                {
                    b.HasOne("Feedlot.Domain.Entities.Animal", null)
                        .WithMany("Pesajes")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.RacionIngrediente", b =>
                {
                    b.HasOne("Feedlot.Domain.Entities.Racion", null)
                        .WithMany("Ingredientes")
                        .HasForeignKey("RacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.VentaItem", b =>
                {
                    b.HasOne("Feedlot.Domain.Entities.Venta", null)
                        .WithMany("Items")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feedlot.Infrastructure.Identity.ApplicationUserRole", b =>
                {
                    b.HasOne("Feedlot.Infrastructure.Identity.ApplicationRole", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Feedlot.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.Animal", b =>
                {
                    b.Navigation("EventosSanitarios");

                    b.Navigation("Pesajes");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.Lote", b =>
                {
                    b.Navigation("AnimalesLote");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.Racion", b =>
                {
                    b.Navigation("Ingredientes");
                });

            modelBuilder.Entity("Feedlot.Domain.Entities.Venta", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Feedlot.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Feedlot.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
